"""initial

Revision ID: 755ed795423b
Revises: 
Create Date: 2023-06-13 18:18:35.586546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755ed795423b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
