"""final

Revision ID: e3e6b25a315f
Revises: bb20db481f42
Create Date: 2023-06-13 19:10:57.835783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e6b25a315f'
down_revision = 'bb20db481f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
