version: '3.8'

services:
  user:
    build: ./user
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./user:/user
    ports:
      - 8000:8000
    depends_on:
      - user-db
    networks:
      - default

  user-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

volumes:
  postgres_data:

networks:
    default: