"""DDD

Revision ID: 2041651946d0
Revises: f470c987191c
Create Date: 2023-06-24 19:15:38.517960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2041651946d0'
down_revision = 'f470c987191c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choices_page_id_fkey', 'choices', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('choices_page_id_fkey', 'choices', 'pages', ['page_id'], ['id'])
    # ### end Alembic commands ###
