"""DDD

Revision ID: 2a0cb1950365
Revises: a378ecb672ac
Create Date: 2023-06-24 14:15:33.913276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0cb1950365'
down_revision = 'a378ecb672ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
