"""DDD

Revision ID: 3087500e9e25
Revises: 2482d343f58e
Create Date: 2023-06-24 14:12:53.878434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3087500e9e25'
down_revision = '2482d343f58e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
