"""DDD

Revision ID: 44df8190d087
Revises: 0780d66966a4
Create Date: 2023-06-24 14:35:32.949472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44df8190d087'
down_revision = '0780d66966a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
