"""DDD

Revision ID: 82e28c43ab9e
Revises: e2920331450a
Create Date: 2023-06-24 14:30:30.480525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e28c43ab9e'
down_revision = 'e2920331450a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
