"""DDD

Revision ID: 944184c3ac61
Revises: 38a938d8932d
Create Date: 2023-06-24 19:01:02.893270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944184c3ac61'
down_revision = '38a938d8932d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
