"""DDD

Revision ID: c88bfe14b6a8
Revises: de7637af08c8
Create Date: 2023-06-24 19:09:48.742786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88bfe14b6a8'
down_revision = 'de7637af08c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
