"""DDD

Revision ID: e104e7419fa6
Revises: 2a0cb1950365
Create Date: 2023-06-24 14:16:37.466699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e104e7419fa6'
down_revision = '2a0cb1950365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
