"""DDD migration

Revision ID: 4dab4bcca346
Revises: b4f62d8bc44f
Create Date: 2023-06-30 16:30:17.009648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dab4bcca346'
down_revision = 'b4f62d8bc44f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('sentences', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audios', 'sentences')
    # ### end Alembic commands ###
