"""DDD

Revision ID: 0780d66966a4
Revises: 8a36864a007f
Create Date: 2023-06-24 14:34:04.843505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0780d66966a4'
down_revision = '8a36864a007f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
