"""DDD

Revision ID: 3522d76a248e
Revises: e104e7419fa6
Create Date: 2023-06-24 14:17:10.795432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3522d76a248e'
down_revision = 'e104e7419fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
