"""DDD

Revision ID: 36a1d0a115a2
Revises: 201a277934b5
Create Date: 2023-06-24 19:02:26.304186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a1d0a115a2'
down_revision = '201a277934b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
