"""DDD

Revision ID: 42abbb911a67
Revises: 3522d76a248e
Create Date: 2023-06-24 14:22:53.498421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42abbb911a67'
down_revision = '3522d76a248e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
