"""DDD

Revision ID: 8a36864a007f
Revises: 82e28c43ab9e
Create Date: 2023-06-24 14:32:15.680985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a36864a007f'
down_revision = '82e28c43ab9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
