"""DDD

Revision ID: a378ecb672ac
Revises: 3087500e9e25
Create Date: 2023-06-24 14:13:46.660074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a378ecb672ac'
down_revision = '3087500e9e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
