"""storychoice

Revision ID: b42a67665b57
Revises: f1ffdda72b79
Create Date: 2023-06-16 16:41:04.221323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b42a67665b57'
down_revision = 'f1ffdda72b79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('story_choice_id_key', 'story_choice', type_='unique')
    op.create_index(op.f('ix_story_choice_id'), 'story_choice', ['id'], unique=False)
    op.create_foreign_key(None, 'story_choice', 'image', ['image_id'], ['id'])
    op.drop_column('story_choice', 'result_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_choice', sa.Column('result_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'story_choice', type_='foreignkey')
    op.drop_index(op.f('ix_story_choice_id'), table_name='story_choice')
    op.create_unique_constraint('story_choice_id_key', 'story_choice', ['id'])
    # ### end Alembic commands ###
