"""DDD

Revision ID: d8f04c6aff6f
Revises: 2041651946d0
Create Date: 2023-06-25 05:59:23.717271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f04c6aff6f'
down_revision = '2041651946d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
