"""DDD

Revision ID: de7637af08c8
Revises: 36a1d0a115a2
Create Date: 2023-06-24 19:02:53.449096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7637af08c8'
down_revision = '36a1d0a115a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
