"""storychoice

Revision ID: f1ffdda72b79
Revises: 3cd9f5d64a0f
Create Date: 2023-06-16 16:37:49.834395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1ffdda72b79'
down_revision = '3cd9f5d64a0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_choice', sa.Column('result_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_index('ix_story_choice_id', table_name='story_choice')
    op.create_unique_constraint(None, 'story_choice', ['id'])
    op.drop_constraint('story_choice_image_id_fkey', 'story_choice', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('story_choice_image_id_fkey', 'story_choice', 'image', ['image_id'], ['id'])
    op.drop_constraint(None, 'story_choice', type_='unique')
    op.create_index('ix_story_choice_id', 'story_choice', ['id'], unique=False)
    op.drop_column('story_choice', 'result_id')
    # ### end Alembic commands ###
