"""DDD

Revision ID: f470c987191c
Revises: c88bfe14b6a8
Create Date: 2023-06-24 19:14:09.766429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f470c987191c'
down_revision = 'c88bfe14b6a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
