version: '3.8'

services:
  streaming:
    build: ./web
    command: bash -c "uvicorn app.application.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./web:/streaming
    env_file:
      - ./web/.env
    depends_on:
      - streaming-db
    networks:
      - default

  streaming-db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streaming
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
