"""remove

Revision ID: 89e0b3755688
Revises: e11cc090244d
Create Date: 2023-06-13 18:35:14.663924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e0b3755688'
down_revision = 'e11cc090244d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
