"""final

Revision ID: dbe047abdcb5
Revises: e3e6b25a315f
Create Date: 2023-06-13 19:13:13.939327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe047abdcb5'
down_revision = 'e3e6b25a315f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
